USE [master]
GO
/****** Object:  Database [Unified]    Script Date: 14/11/2025 10:52:40 p. m. ******/
CREATE DATABASE [Unified]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Unified', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Unified.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Unified_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Unified_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Unified] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Unified].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Unified] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Unified] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Unified] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Unified] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Unified] SET ARITHABORT OFF 
GO
ALTER DATABASE [Unified] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Unified] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Unified] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Unified] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Unified] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Unified] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Unified] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Unified] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Unified] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Unified] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Unified] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Unified] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Unified] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Unified] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Unified] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Unified] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Unified] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Unified] SET RECOVERY FULL 
GO
ALTER DATABASE [Unified] SET  MULTI_USER 
GO
ALTER DATABASE [Unified] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Unified] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Unified] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Unified] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Unified] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Unified] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Unified', N'ON'
GO
ALTER DATABASE [Unified] SET QUERY_STORE = ON
GO
ALTER DATABASE [Unified] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Unified]
GO
/****** Object:  Table [dbo].[Carrera]    Script Date: 14/11/2025 10:52:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Carrera](
	[IdCarrera] [int] IDENTITY(1,1) NOT NULL,
	[NombreCarrera] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Carrera] PRIMARY KEY CLUSTERED 
(
	[IdCarrera] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Correo]    Script Date: 14/11/2025 10:52:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Correo](
	[IdCorreo] [int] IDENTITY(1,1) NOT NULL,
	[Correo] [varchar](70) NOT NULL,
 CONSTRAINT [PK_Correo] PRIMARY KEY CLUSTERED 
(
	[IdCorreo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estudiante]    Script Date: 14/11/2025 10:52:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estudiante](
	[IdEstudiante] [int] IDENTITY(1,1) NOT NULL,
	[NombreEstudiante] [varchar](100) NOT NULL,
	[CCEstudiante] [int] NOT NULL,
	[IdCorreo] [int] NOT NULL,
	[IdCarrera] [int] NOT NULL,
 CONSTRAINT [PK_Estudiante] PRIMARY KEY CLUSTERED 
(
	[IdEstudiante] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Materia]    Script Date: 14/11/2025 10:52:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Materia](
	[IdMateria] [int] IDENTITY(1,1) NOT NULL,
	[NombreMateria] [varchar](50) NOT NULL,
	[IdCarrera] [int] NOT NULL,
 CONSTRAINT [PK_Materia] PRIMARY KEY CLUSTERED 
(
	[IdMateria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Material]    Script Date: 14/11/2025 10:52:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Material](
	[IdMaterial] [int] IDENTITY(1,1) NOT NULL,
	[TipoMaterial] [varchar](50) NOT NULL,
	[IdMateria] [int] NOT NULL,
 CONSTRAINT [PK_Material] PRIMARY KEY CLUSTERED 
(
	[IdMaterial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Profesor]    Script Date: 14/11/2025 10:52:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profesor](
	[IdProfesor] [int] IDENTITY(1,1) NOT NULL,
	[NombreProfesor] [varchar](100) NOT NULL,
	[CCProfesor] [int] NOT NULL,
	[IdCorreo] [int] NOT NULL,
 CONSTRAINT [PK_Profesor] PRIMARY KEY CLUSTERED 
(
	[IdProfesor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Profesor-Materia]    Script Date: 14/11/2025 10:52:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profesor-Materia](
	[IdProfesor] [int] NOT NULL,
	[IdMateria] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Estudiante]  WITH NOCHECK ADD  CONSTRAINT [FK_Estudiante_Carrera] FOREIGN KEY([IdEstudiante])
REFERENCES [dbo].[Carrera] ([IdCarrera])
GO
ALTER TABLE [dbo].[Estudiante] NOCHECK CONSTRAINT [FK_Estudiante_Carrera]
GO
ALTER TABLE [dbo].[Estudiante]  WITH CHECK ADD  CONSTRAINT [FK_Estudiante_Correo] FOREIGN KEY([IdCorreo])
REFERENCES [dbo].[Correo] ([IdCorreo])
GO
ALTER TABLE [dbo].[Estudiante] CHECK CONSTRAINT [FK_Estudiante_Correo]
GO
ALTER TABLE [dbo].[Materia]  WITH CHECK ADD  CONSTRAINT [FK_Materia_Carrera] FOREIGN KEY([IdCarrera])
REFERENCES [dbo].[Carrera] ([IdCarrera])
GO
ALTER TABLE [dbo].[Materia] CHECK CONSTRAINT [FK_Materia_Carrera]
GO
ALTER TABLE [dbo].[Material]  WITH CHECK ADD  CONSTRAINT [FK_Material_Materia] FOREIGN KEY([IdMateria])
REFERENCES [dbo].[Materia] ([IdMateria])
GO
ALTER TABLE [dbo].[Material] CHECK CONSTRAINT [FK_Material_Materia]
GO
ALTER TABLE [dbo].[Profesor]  WITH CHECK ADD  CONSTRAINT [FK_Profesor_Correo] FOREIGN KEY([IdCorreo])
REFERENCES [dbo].[Correo] ([IdCorreo])
GO
ALTER TABLE [dbo].[Profesor] CHECK CONSTRAINT [FK_Profesor_Correo]
GO
ALTER TABLE [dbo].[Profesor-Materia]  WITH CHECK ADD  CONSTRAINT [FK_Profesor-Materia_Materia] FOREIGN KEY([IdMateria])
REFERENCES [dbo].[Materia] ([IdMateria])
GO
ALTER TABLE [dbo].[Profesor-Materia] CHECK CONSTRAINT [FK_Profesor-Materia_Materia]
GO
ALTER TABLE [dbo].[Profesor-Materia]  WITH CHECK ADD  CONSTRAINT [FK_Profesor-Materia_Profesor] FOREIGN KEY([IdProfesor])
REFERENCES [dbo].[Profesor] ([IdProfesor])
GO
ALTER TABLE [dbo].[Profesor-Materia] CHECK CONSTRAINT [FK_Profesor-Materia_Profesor]
GO
USE [master]
GO
ALTER DATABASE [Unified] SET  READ_WRITE 
GO
